language: node_js
node_js:
  - stable
before_script:
   - npm install -g @angular/cli
script:
   - ng build --prod --bh /projet-front/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
