language: node_js
node_js:
  - "stable"

before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --bh /projet_front-end/


deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
